apiVersion: v1
kind: Namespace
metadata:
  name: nps-ml-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nlp-api
  name: nlp-api
  namespace: nps-ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-api
  template:
    metadata:
      labels:
        app: nlp-api
    spec:
      containers:
      - image: fabriziossr/nlp_api:latest  # Your specified image
        name: nlp-api
        ports:
        - containerPort: 8000  # Change to match your FastAPI port
---
apiVersion: v1
kind: Service
metadata:
  name: nlp-api-lb
  labels:
    app: nlp-api
  namespace: nps-ml-app
spec:
  type: LoadBalancer
  ports:
  - port: 80  # External port
    targetPort: 8000  # Internal port
  selector:
    app: nlp-api